server {
    listen 80;
    server_name cse-aisearchinterface-dev-web-01.oit.umn.edu;

    # TODO: set this to the absolute path of vueAISearch/dist on the VM
    root /TODO/REPO/PATH/vueAISearch/dist;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/serp {
        proxy_pass http://127.0.0.1:3001;
        proxy_set_header Host $host;
    }
}
